version: "3.8"

services:
  client:
    build:
      context: ./client
      args:
        VITE_API_URL: "http://localhost:3000/api"
        VITE_WS_URL: "http://localhost:3000"
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      DATABASE: "./db/dev.sqlite"
      OPEN_ROUTER_URL: "https://openrouter.ai/api/v1"
      NODE_ENV: production
    volumes:
      - ./server/db:/app/db
      - ./server/prompts:/app/prompts
    restart: unless-stopped
